#!/bin/bash

set -e
c_echo() {
  tput setaf 3; echo $1
  # set back to normal color
  tput sgr0
}

c_echo "  ____ ____  ______ __ __  ___  ____  __ __ __  _____"
c_echo " /    |    \|      |  |  |/   \|    \|  |  |  |/ ___/"
c_echo "|  o  |  _  |      |  |  |     |  _  |  |  |_ (   \_ "
c_echo "|     |  |  |_|  |_|  _  |  O  |  |  |  ~  | \|\__  |"
c_echo "|  _  |  |  | |  | |  |  |     |  |  |___, |   /  \ |"
c_echo "|  |  |  |  | |  | |  |  |     |  |  |     |   \    |"
c_echo "|__|__|__|__| |__| |__|__|\___/|__|__|____/     \___|"
c_echo "                                                     "
c_echo " ___    ___  ______      _____ ____ _       ___ _____"
c_echo "|   \  /   \|      |    |     |    | |     /  _] ___/"
c_echo "|    \|     |      |    |   __||  || |    /  [(   \_ "
c_echo "|  D  |  O  |_|  |_|    |  |_  |  || |___|    _]__  |"
c_echo "|     |     | |  |      |   _] |  ||     |   [_/  \ |"
c_echo "|     |     | |  |      |  |   |  ||     |     \    |"
c_echo "|_____|\___/  |__|      |__|  |____|_____|_____|\___|"

c_echo "==> Here we go..."
c_echo "==> Thanks to Chris Hunt and others for making these files so great!"
cd ~

install_for_osx(){
  c_c_echo "  > Updating homebrew..."
  brew update &> /dev/null

  c_echo "  > Installing reattach-to-user-namespace..."
  if command -v reattach-to-user-namespace >/dev/null 2>&1; then
    c_echo "    > (Skipping) Already installed."
  else
    brew install reattach-to-user-namespace &> /dev/null
  fi
}

install_for_linux(){
  c_echo "Linux detected, updating pacakges..."
  sudo apt-get update        # Fetches the list of available updates
  sudo apt-get upgrade       # Strictly upgrades the current packages
  sudo apt-get dist-upgrade  # Installs updates (new ones)
  c_echo "Installing Git..."
  sudo apt-get install git-core
  c_echo "Removing system vim and replacing it with gtk"
  sudo apt-get purge vim gvim vim-gtk
  sudo apt-get install vim-gtk
  c_echo "Installing tmux..."
  sudo apt-get install tmux
  c_echo "Installing zsh"
  sudo apt-get install zsh
  c_echo "Setting zsh as default shell"
  chsh -s /bin/zsh
  c_echo "Installing oh-my-zsh"
  sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -0 -)"
  c_echo "Symlinking dot files"
  files=( ".vimrc" ".vim" ".tmux.conf" ".zshrc" ".gitconfig" ".gitmessage" )
  for i in "${#array[@]}"
  do
    c_echo "Linking $i"
    ln -s ~/dotfiles/"$i" ~/"$i"
  done
}

case "$OSTYPE" in
  darwin*)  install_for_osx ;;
  linux*)   install_for_linux ;;
  *)        c_echo "unknown: $OSTYPE" ;;
esac

# move into dotfiles and pull down vim and oh-my-zsh
cd ~/dotfiles
c_echo "  > Updating all git submodules..."
git submodule init
git submodule update
git config alias.supdate; git submodule update --remote --merge;

c_echo "Reloading shell.."
source ~/.zshrc
c_echo "==> Done with setup."
