#!/bin/bash

set -e
c_echo() {
  tput setaf 3; echo $1
  # set back to normal color
  tput sgr0
}

echo "  ____ ____  ______ __ __  ___  ____  __ __ __  _____"
echo " /    |    \|      |  |  |/   \|    \|  |  |  |/ ___/"
echo "|  o  |  _  |      |  |  |     |  _  |  |  |_ (   \_ "
echo "|     |  |  |_|  |_|  _  |  O  |  |  |  ~  | \|\__  |"
echo "|  _  |  |  | |  | |  |  |     |  |  |___, |   /  \ |"
echo "|  |  |  |  | |  | |  |  |     |  |  |     |   \    |"
echo "|__|__|__|__| |__| |__|__|\___/|__|__|____/     \___|"
echo "                                                     "
echo " ___    ___  ______      _____ ____ _       ___ _____"
echo "|   \  /   \|      |    |     |    | |     /  _] ___/"
echo "|    \|     |      |    |   __||  || |    /  [(   \_ "
echo "|  D  |  O  |_|  |_|    |  |_  |  || |___|    _]__  |"
echo "|     |     | |  |      |   _] |  ||     |   [_/  \ |"
echo "|     |     | |  |      |  |   |  ||     |     \    |"
echo "|_____|\___/  |__|      |__|  |____|_____|_____|\___|"

c_echo "==> Here we go..."
c_echo "==> Thanks to Chris Hunt and others for making these files so great!"
cd ~

install_for_osx(){
  c_c_echo "  > Updating homebrew..."
  brew update &> /dev/null

  c_echo "  > Installing reattach-to-user-namespace..."
  if command -v reattach-to-user-namespace >/dev/null 2>&1; then
    c_echo "    > (Skipping) Already installed."
  else
    brew install reattach-to-user-namespace &> /dev/null
  fi
}

install_for_linux(){
  c_echo "Linux detected, updating pacakges..."
  apt-get -y update        # Fetches the list of available updates
  apt-get -y upgrade       # Strictly upgrades the current packages
  apt-get -y dist-upgrade  # Installs updates (new ones)
  c_echo "Installing Git..."
  apt-get -y install git-core
  c_echo "Removing system vim and replacing it with gtk"
  apt-get -y purge vim gvim vim-gtk
  apt-get -y install vim-gtk
  c_echo "Installing tmux..."
  apt-get -y install tmux
  c_echo "Installing silver searcher"
  apt-get -y install silversearcher-ag
  c_echo "Installing zsh"
  apt-get -y install zsh
  c_echo "Setting zsh as default shell"
  chsh -s /bin/zsh
  c_echo "Installing oh-my-zsh"
  ( exec wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - )
  c_echo "Symlinking dot files"
  for file in ".vimrc" ".vim" ".tmux.conf" ".zshrc" ".gitconfig" ".gitmessage"
  do
    c_echo "Linking $file"
    ln -s ~/dotfiles/"$file" ~/"$file"
  done
}

case "$OSTYPE" in
  darwin*)  install_for_osx ;;
  linux*)   install_for_linux ;;
  *)        c_echo "unknown: $OSTYPE" ;;
esac

# move into dotfiles and pull down vim and oh-my-zsh
cd ~/dotfiles
c_echo "  > Updating all git submodules..."
git submodule init
git submodule update
git config alias.supdate; git submodule update --remote --merge;

c_echo "Reloading shell.."
source ~/.zshrc
c_echo "==> Done with setup."
