#!/bin/sh

set -e

echo "  ____ ____  ______ __ __  ___  ____  __ __ __  _____"
echo " /    |    \|      |  |  |/   \|    \|  |  |  |/ ___/"
echo "|  o  |  _  |      |  |  |     |  _  |  |  |_ (   \_ "
echo "|     |  |  |_|  |_|  _  |  O  |  |  |  ~  | \|\__  |"
echo "|  _  |  |  | |  | |  |  |     |  |  |___, |   /  \ |"
echo "|  |  |  |  | |  | |  |  |     |  |  |     |   \    |"
echo "|__|__|__|__| |__| |__|__|\___/|__|__|____/     \___|"
echo "                                                     "
echo " ___    ___  ______      _____ ____ _       ___ _____"
echo "|   \  /   \|      |    |     |    | |     /  _] ___/"
echo "|    \|     |      |    |   __||  || |    /  [(   \_ "
echo "|  D  |  O  |_|  |_|    |  |_  |  || |___|    _]__  |"
echo "|     |     | |  |      |   _] |  ||     |   [_/  \ |"
echo "|     |     | |  |      |  |   |  ||     |     \    |"
echo "|_____|\___/  |__|      |__|  |____|_____|_____|\___|"

echo "==> Here we go..."
cd ~

echo "  > Updating homebrew..."
brew update &> /dev/null

echo "  > Installing reattach-to-user-namespace..."
if command -v reattach-to-user-namespace >/dev/null 2>&1; then
  echo "    > (Skipping) Already installed."
else
  brew install reattach-to-user-namespace &> /dev/null
fi

echo "  > Pulling latest dot-files..."
git pull &> /dev/null

echo "  > Updating all git submodules..."
git submodule init &> /dev/null
git submodule update &> /dev/null

echo "==> Done with setup."
