#! /bin/bash

echo "
\" this is slightly destructive and should only be used when the JSON
\" *has_not_already_been_formmatted/indented*
function! IndentJSON()
  \" add new line after comma
  %s/\(,\)/\1\r/g
  \" add new line after open brace
  %s/\({\)/\1\r/g
  \" add new line before closing brace
  %s/\(}\)/\r\1/g
  \" add new line after open bracket
  %s/\(\[\)/\1\r/g
  \" add new line before closing bracket
  %s/\(\]\)/\r\1/g
  \" remove blank lines
  g/^\s*$/d
  \" indent the file
  norm gg=G
endfunction

map <leader>js :call IndentJSON() <cr>
" >> ~/.vimrc_local

echo "
\"ctag everything in current directory and gems
function! Ctag()
  let ruby = match(expand("%"), ".rb")
  let go = match(expand("%"), ".go")
  if ruby != -1
    exec ":!ctags -R --languages=ruby --exclude=.git --exclude=log . $(bundle list --paths)"
  endif
endfunction

map <leader>rt :call Ctag()<cr>
" >> ~/.vimrc_local

echo "
\"toggle insert and normal mode
imap ii <C-[>
" >> ~/.vimrc_local

