#! /bin/bash

endpoint=$1

get_ext() {
  case $1 in
    *github*)
      case $endpoint in
        pr)
          echo "/pulls";;
        issues)
          echo "/issues";;
        *)
          echo ;;
      esac;;
    *bitbucket*)
      case $endpoint in
        pr)
          echo "/pull-requests";;
        issues)
          # issues aren't enabled by default for bb repos
          # so this might not always work
          echo "/issues";;
        *)
          echo ;;
      esac;;
  esac
}

open_site() {
  ext=$(get_ext $1)
  url=""
  if [[ $remote == *@* ]]; then
    # extract path from ssh
    name=$(echo "$remote" | sed  "s/^.*:\(.*\)\.git/\1/g")
    url="$1/${name}${ext}"
  else
    # extract uri from http
    name=$(echo "$remote" | sed "s/^.*: \(.*\).git/\1/g")
    url="${name}${ext}"
  fi
  open "$url"
}

# get remote from origin
remote=$(git remote show -n origin | grep Fetch.URL)

case $remote in
  *github*)
    open_site "https://github.com";;
  *bitbucket*)
    open_site "https://bitbucket.org";;
esac
